databases:
  - name: bulletin_board_pg_instance
    databaseName: db_bulletin_board
    user: db_bulletin_board_user
    plan: free

services:
  - type: web
    name: BulletinBoard
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bulletin_board_pg_instance
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
